version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - SECRET_KEY=django-insecure-oe9!^5%r*mis@8s))wz0(y^qq#^re+#hgmdxx*0m4g9q_ytyfp

volumes:
  static_volume:
  media_volume: